import { 
  AdminUser, 
  Product, 
  Order, 
  PaymentLog, 
  TeamMember, 
  Realisation, 
  Article, 
  Partner, 
  JobOffer, 
  Application 
} from '../types';

export const INITIAL_USERS: AdminUser[] = [
  {
    id: 'u1',
    email: 'admin@serein-ge.bf',
    nom_complet: 'Patrice COMPAORÉ (Directeur)',
    role: 'super_admin',
    avatar_url: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?auto=format&fit=crop&w=200&q=80',
    telephone: '+226 25 30 00 01',
    is_active: true,
    created_at: '2026-01-15',
  },
  {
    id: 'u2',
    email: 'editeur@serein-ge.bf',
    nom_complet: 'Yacouba SANOU (Commercial)',
    role: 'editeur',
    avatar_url: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=200&q=80',
    telephone: '+226 25 30 00 04',
    is_active: true,
    created_at: '2026-03-10',
  }
];

export const INITIAL_PRODUCTS: Product[] = [
  {
    id: 'p1',
    nom: 'CHCNAV i90 GNSS RTK IMU',
    slug: 'chcnav-i90-gnss-rtk-imu',
    marque: 'CHCNAV',
    categorie: 'Récepteurs GNSS RTK',
    description_courte: 'Récepteur GNSS multi-constellations haut de gamme avec centrale inertielle IMU sans étalonnage et modem 4G/UHF intégré.',
    description_complete: 'Le CHCNAV i90 intègre les dernières technologies GNSS de pointe avec 624 canaux de suivi toutes constellations.',
    prix_fcfa: 4250000,
    prix_promo_fcfa: 3950000,
    stock: 6,
    stock_alerte: 2,
    images: ['https://images.unsplash.com/photo-1581092160607-ee22621dd758?auto=format&fit=crop&w=800&q=80'],
    specs_techniques: { 'Canaux': '624', 'Précision RTK': '8mm + 1ppm', 'IMU': '60°', 'Radio': 'UHF 2W' },
    en_vedette: true,
    is_active: true,
  },
  {
    id: 'p2',
    nom: 'Toknav T20 Pro GNSS avec Caméra AR & IMU',
    slug: 'toknav-t20-pro-gnss-ar-imu',
    marque: 'Toknav',
    categorie: 'Récepteurs GNSS RTK',
    description_courte: 'Récepteur GNSS révolutionnaire avec double caméra pour implantation visuelle en réalité augmentée.',
    description_complete: 'Le Toknav T20 Pro redéfinit le travail de l\'opérateur terrain grâce à son module de caméra haute définition.',
    prix_fcfa: 4850000,
    prix_promo_fcfa: null,
    stock: 4,
    stock_alerte: 1,
    images: ['https://images.unsplash.com/photo-1581092335397-9583fe92d232?auto=format&fit=crop&w=800&q=80'],
    specs_techniques: { 'Canaux': '1408', 'AR Stakeout': 'Double Caméra', 'Poids': '790g' },
    en_vedette: true,
    is_active: true,
  },
  {
    id: 'p3',
    nom: 'Station Totale FOIF RTS352 Reflectorless 1000m',
    slug: 'station-totale-foif-rts352-1000m',
    marque: 'FOIF',
    categorie: 'Stations Totales',
    description_courte: 'Station totale de haute précision angulaire 2" avec mesure sans prisme jusqu\'à 1000 mètres.',
    description_complete: 'La station totale FOIF RTS352 est l\'équipement de référence pour les chantiers de construction.',
    prix_fcfa: 3750000,
    prix_promo_fcfa: null,
    stock: 1, // Alerte stock faible
    stock_alerte: 2,
    images: ['https://images.unsplash.com/photo-1503387762-592deb58ef4e?auto=format&fit=crop&w=800&q=80'],
    specs_techniques: { 'Précision': '2"', 'Portée sans prisme': '1000m' },
    en_vedette: true,
    is_active: true,
  },
  {
    id: 'p4',
    nom: 'Drone DJI Matrice 350 RTK avec Zenmuse L2 LiDAR',
    slug: 'dji-matrice-350-rtk-zenmuse-l2-lidar',
    marque: 'DJI Enterprise',
    categorie: 'Drones & LiDAR',
    description_courte: 'Solution de cartographie aérienne et scanner LiDAR 3D de précision centimétrique.',
    description_complete: 'Le combo DJI Matrice 350 RTK couplé au capteur LiDAR Zenmuse L2.',
    prix_fcfa: 18500000,
    prix_promo_fcfa: 17500000,
    stock: 2,
    stock_alerte: 1,
    images: ['https://images.unsplash.com/photo-1527977966376-1c8408f9f108?auto=format&fit=crop&w=800&q=80'],
    specs_techniques: { 'Vol': '55 min', 'LiDAR': '450m', 'Impulsions': '240k pts/s' },
    en_vedette: true,
    is_active: true,
  }
];

export const INITIAL_ORDERS: Order[] = [
  {
    id: 'o1',
    reference: 'SER-26-8921',
    client_nom: 'Moussa BAZIÉ (BTP Faso)',
    client_email: 'mbazie@btpfaso.bf',
    client_telephone: '+226 70 12 34 56',
    client_entreprise: 'BTP Faso Construction',
    adresse_livraison: 'Zone Industrielle de Kossodo, Ouagadougou',
    ville: 'Ouagadougou',
    pays: 'Burkina Faso',
    total_fcfa: 3950000,
    statut: 'paid',
    mode_paiement: 'cinetpay',
    created_at: '2026-08-28T10:15:00Z',
    items: [
      {
        id: 'oi1',
        order_id: 'o1',
        product_nom: 'CHCNAV i90 GNSS RTK IMU',
        product_marque: 'CHCNAV',
        quantite: 1,
        prix_unitaire_fcfa: 3950000,
        total_ligne_fcfa: 3950000,
      }
    ]
  },
  {
    id: 'o2',
    reference: 'SER-26-8920',
    client_nom: 'Dr. Salif DIALLO (Mines)',
    client_email: 'sdiallo@goldmining.bf',
    client_telephone: '+226 78 90 12 34',
    client_entreprise: 'Société Minière de Houndé',
    adresse_livraison: 'Site minier de Houndé, Tuy',
    ville: 'Houndé',
    pays: 'Burkina Faso',
    total_fcfa: 4850000,
    statut: 'processing',
    mode_paiement: 'cinetpay',
    created_at: '2026-08-27T14:40:00Z',
    items: [
      {
        id: 'oi2',
        order_id: 'o2',
        product_nom: 'Toknav T20 Pro GNSS avec Caméra AR & IMU',
        product_marque: 'Toknav',
        quantite: 1,
        prix_unitaire_fcfa: 4850000,
        total_ligne_fcfa: 4850000,
      }
    ]
  },
  {
    id: 'o3',
    reference: 'SER-26-8919',
    client_nom: 'Cabinet Géomètre Ouedraogo',
    client_email: 'contact@geometre-oued.bf',
    client_telephone: '+226 76 54 32 10',
    adresse_livraison: 'Secteur 28, Bobo-Dioulasso',
    ville: 'Bobo-Dioulasso',
    pays: 'Burkina Faso',
    total_fcfa: 3750000,
    statut: 'shipped',
    mode_paiement: 'virement',
    created_at: '2026-08-25T09:20:00Z',
    items: [
      {
        id: 'oi3',
        order_id: 'o3',
        product_nom: 'Station Totale FOIF RTS352 Reflectorless 1000m',
        product_marque: 'FOIF',
        quantite: 1,
        prix_unitaire_fcfa: 3750000,
        total_ligne_fcfa: 3750000,
      }
    ]
  }
];

export const INITIAL_PAYMENT_LOGS: PaymentLog[] = [
  {
    id: 'pl1',
    order_id: 'o1',
    order_ref: 'SER-26-8921',
    provider: 'cinetpay',
    transaction_id: 'CPAY_BF_20260828_99812',
    montant_fcfa: 3950000,
    statut: 'SUCCESS',
    operateur: 'ORANGE_MONEY_BF',
    created_at: '2026-08-28T10:17:32Z',
    callback_raw: { code: '00', message: 'SUCCES', operator_id: 'OM_BF_892144' },
  },
  {
    id: 'pl2',
    order_id: 'o2',
    order_ref: 'SER-26-8920',
    provider: 'cinetpay',
    transaction_id: 'CPAY_BF_20260827_77410',
    montant_fcfa: 4850000,
    statut: 'SUCCESS',
    operateur: 'MOOV_MONEY_BF',
    created_at: '2026-08-27T14:42:15Z',
    callback_raw: { code: '00', message: 'SUCCES', operator_id: 'MOOV_BF_441209' },
  },
  {
    id: 'pl3',
    order_id: 'o3',
    order_ref: 'SER-26-8919',
    provider: 'direct',
    transaction_id: 'VIR_CORIS_20260825_11',
    montant_fcfa: 3750000,
    statut: 'SUCCESS',
    operateur: 'VIREMENT_CORIS_BANK',
    created_at: '2026-08-25T09:30:00Z',
  }
];

export const INITIAL_APPLICATIONS: Application[] = [
  {
    id: 'app1',
    poste_souhaite: 'Ingénieur Géomètre-Topographe Senior (H/F)',
    type_candidature: 'sur_offre',
    civilite: 'M.',
    nom: 'SAWADOGO',
    prenom: 'Abdoulaye',
    email: 'a.sawadogo@gmail.com',
    telephone: '+226 70 88 99 00',
    niveau_etude: 'Ingénieur (BAC+5 - 2iE)',
    annees_experience: 6,
    cv_url: 'https://storage.serein-ge.bf/cvs/cv_sawadogo_2026.pdf',
    message: 'Titulaire d\'un diplôme d\'ingénieur géomètre de l\'école 2iE avec 6 ans d\'expérience sur les chantiers d\'infrastructures.',
    statut: 'en_revue',
    notes_recruteur: 'Excellent profil technique, à inviter pour entretien technique.',
    created_at: '2026-08-26',
  },
  {
    id: 'app2',
    poste_souhaite: 'Technico-Commercial Vente Matériel Topographique & Drones',
    type_candidature: 'sur_offre',
    civilite: 'Mme',
    nom: 'KABORÉ',
    prenom: 'Fatoumata',
    email: 'fatou.kabore@yahoo.fr',
    telephone: '+226 78 11 22 33',
    niveau_etude: 'Licence Commerciale & SIG',
    annees_experience: 4,
    cv_url: 'https://storage.serein-ge.bf/cvs/cv_kabore_fatou.pdf',
    message: 'Forte d\'une expérience de 4 ans dans la commercialisation d\'équipements techniques et solutions logicielles.',
    statut: 'entretien',
    notes_recruteur: 'Entretien fixé pour le 2 septembre 2026 à 10h au siège.',
    created_at: '2026-08-24',
  }
];
